### ISSUE TITLE
Add RetryResultLogger utility class

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi#248]

**Comment by sleberknight** [comment]
@chrisrohr do you agree with leaving the name as `RetryResultLogger` instead of making it `KiwiRetryResultLogger` for the reason that this seems to make it more clear this is directly related to `RetryResult` ?

**Comment by chrisrohr** [comment]
> @chrisrohr do you agree with leaving the name as `RetryResultLogger` instead of making it `KiwiRetryResultLogger` for the reason that this seems to make it more clear this is directly related to `RetryResult` ?

Sure that sounds reasonable
