### ISSUE TITLE
Consider adding new KiwiPreconditions methods to throw illegal arg instead of illegal state

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi#457]
The new methods like `checkPositive`, `checkPositiveOrZero`, etc. all throw `IllegalStateException`, which seems a little odd when used to check a method _argument_.

We might consider leaving these methods alone, but _adding_ new methods that throw `IllegalArgumentException` and have the word `Argument` in their name to make the intent more clear, e.g. `checkArgumentPositive(arg)` vs `checkPositive(someValue)`.

This way we can have the (more) appropriate exception thrown for argument checking (`IllegalArgumentException`) and also permit state checking within a method.

**Comment by sleberknight** [comment]
Might also be nice to have methods that check collections, e.g. `checkListNotEmpty`, `checkSetNotEmpty`, and so on.

**Comment by sleberknight** [comment]
Here are the base methods (i.e. not listing all overloads) that throw `IllegalStateException` currently, and which this issue proposes to add argument check variants that throw `IllegalArgumentException`:

* checkEvenItemCount
* checkPositive
* requirePositive
* checkPositiveOrZero
* requirePositiveOrZero
* checkValidPort
* requireValidPort
* checkValidNonZeroPort
* requireValidNonZeroPort

The new methods corresponding to the above would then be:

| Existing base method | New base method |
| --- | --- |
| checkEvenItemCount | checkArgumentEvenItemCount |
| checkPositive | checkArgumentPositive |
| requirePositive | requireArgumentPositive |
| checkPositiveOrZero | checkArgumentPositiveOrZero |
| requirePositiveOrZero | requireArgumentPositiveOrZero |
| checkValidPort | checkArgumentValidPort |
| requireValidPort | requireArgumentValidPort |
| checkValidNonZeroPort | checkArgumentValidNonZeroPort |
| requireValidNonZeroPort | requireArgumentValidNonZeroPort |

This will add a _lot_ of new methods, since each base method typically has 3 (or more in certain cases like the base methods that accept `int` or `long` each with 3 overloads).

Here are the current overload counts for each existing base method above:

| Existing base method | Overload count |
| --- | --- |
| checkEvenItemCount | 3 |
| checkPositive | 6 |
| requirePositive | 6 |
| checkPositiveOrZero | 6 |
| requirePositiveOrZero | 6 |
| checkValidPort | 3 |
| requireValidPort | 3 |
| checkValidNonZeroPort | 3 |
| requireValidNonZeroPort | 3 |
|  **Total method count** | **39** |

This means we will add _39 more_ methods to `KiwiPreconditions` to complete this issue. I'm not sure it is really worth doing just to be able to get an `IllegalArgumentException` instead of an `IllegalStateException`. If an `IllegalArgumentException` is _really_ needed instead of `IllegalStateException`, we can always fall back to the regular Guava `Preconditions` class or just do an old-school manual check-and-throw.

I would be more interested in adding a few methods related to collections (as I mentioned in an earlier comment e.g. `checkListNotEmpty`, etc.). There could be variants for any `Collection` (`List` or `Set`) as well as `Map`. For example `checkArgumentNotEmpty` that has overloads accepting a `Collection` or a `Map`.

I recently needed to validate several `Collection` arguments, and used Guava's `Preconditions` and our `KiwiSets` with static imports, e.g.: `checkArgument(isNotNullOrEmpty(coll))`. This is pretty succinct so not sure whether it's even worth adding more methods to be able to do `checkArgumentNotEmpty(coll)`.

**Comment by chrisrohr** [comment]
Just add the new variants and not the IllegalArgument ones

**Comment by sleberknight** [comment]
Which new variants? Do you mean only a few related to validating collection and map arguments?

**Comment by sleberknight** [comment]
OK, I will create a new issue that contains only a few collection-related argument check methods, then close this issue as "Won't Do".

**Comment by sleberknight** [comment]
Created #753 to add collection and map argument check methods.

Closing this now as "Won't Do"
