### ISSUE TITLE
Suggestion: Make KiwiMaps.newTreeMap return a SortedMap instead of just Map

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/kiwi#484]
There are a number of instances where libraries need SortedMap instances and using `newTreeMap` returns a Map which causes compile time issues. Since TreeMap implements SortedMap which implements Map, this should work in most cases.

**Comment by sleberknight** [comment]
Odd...I just looked at the original (internal) `KiwiMaps` and that method returns `Map`_not_ `SortedMap`, so how did it work internally in the places where we now have been forced to cast to `SortedMap`?

**Comment by sleberknight** [comment]
So I can remember, we first encountered the need to cast to a `SortedMap` in `dropwizard-service-utilities` in the `HttpConnectionsHealthCheckTest`

**Comment by sleberknight** [comment]
Signature should be:

```java
public static <K extends Comparable, V> SortedMap<K, V> newTreeMap(Object... items)
```
