### ISSUE TITLE
Consider adding a helper method in KiwiResources to buffer entity and do fromResponse

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi#590]
### Discussed in https://github.com/kiwiproject/kiwi/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **sleberknight** July  9, 2021</sup>
See [this gist](https://gist.github.com/sleberknight/75b40b77c3c69ff0f4258ec56bc6d5c2) for code examples.

Whenever you create a `Response` from the response of another request, i.e. `Response.fromResponse(response).build()`, according to the `Response` Javadocs you _must_ call` bufferEntity` first if the entity from the original response is unconsumed. 

This is one of those things that's really easy to forget about, so maybe we should create a method in `KiwiResources` that does these things for us, e.g. instead of:

```java
// inside a Jakarta RS resource endpoint
var response = makeCallToOtherService();

response.bufferEntity();
return Response.fromResponse(response).build();
```

we could do:

```java
// inside a Jakarta RS resource endpoint
var response = makeCallToOtherService();

return KiwiResources.fromResponseBufferingEntity(response).build();
```

The `fromResponseBufferingEntity` would basically do:

```java
public static fromResponseBufferingEntity(Response originalResponse) {
    originalResponse.bufferEntity();
   return Response.fromResponse(originalResponse);
}
```
</div>

**Comment by sleberknight** [comment]
Hey looking at this again, this works but I'm wondering if the method name isn't really so great. For example:

```java
// inside a resource endpoint method
var response = callOtherService();

return KiwiResources.fromResponseBufferingEntity(response);
```

Is that clear what it's doing? If the method were statically imported, it reads even worse:

```java
// inside a resource endpoint method
var response = callOtherService();

return fromResponseBufferingEntity(response);
```

Though to be fair, I would always use `Response.fromResponse(original)` if using the regular APIs, not `fromResponse(original)`.

In addition, maybe I should have paid closer attention to the existing method naming in this class, e.g. `newResponse` and `createdResponse` and `okResponse` are pretty clear whether statically imported or not, e.g.

```java
// an OK response
return okResponse(anEntity);

// or some other status with an entity and content type
return newResponse(Status.ACCEPTED, anEntity, "application/json");
```

Given all this, maybe these methods would be better named:

* `newResponseBufferingEntityFrom`
* `newResponseBufferingEntityBuilderFrom` (or `newResponseBuilderBufferingEntityFrom`)

These would then read as:

```java
// inside a resource endpoint method
var response = callOtherService();

return KiwiResources.newResponseBufferingEntityFrom(response);
```

and if using the method returning a builder:

```java
// inside a resource endpoint method
var response = callOtherService();

return KiwiResources.newResponseBuilderBufferingEntityFrom(response)
   ...
   .build();
```

Or, maybe I am just overthinking this...thoughts?

**Comment by chrisrohr** [comment]
You are probably overthinking things.... however, I do think the proposed names read better.
